name: reST syntax validity

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt install python3-docutils
      - name: Checking reST validity
        run: |
          for f in $(git ls-files | grep '\.rst'); do
              rst2html --strict $f >/dev/null || exit $?;
          done
